services:
  # Бэкенд сервис
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      # База данных
      - DATABASE_URL=${DATABASE_URL}
      # Redis
      - REDIS_URL=${REDIS_URL}
      # JWT и сессии
      - SECRET_KEY=${SECRET_KEY}
      # Сервер
      - PORT=4000
      - HOST=0.0.0.0
      - DEBUG=${DEBUG:-false}
      # CORS origins для продакшена (задается через Dokploy GUI)
      - EXTERNAL_ORIGINS=${EXTERNAL_ORIGINS}
    ports:
      - "4001:4000"
    volumes:
      # Используем ../files для персистентности данных как рекомендует Dokploy
      - "../files/backend-logs:/app/logs"
      - "../files/backend-uploads:/app/uploads"
    networks:
      - garden-store-network
      - dokploy-network
    labels:
      # Traefik labels для API через тот же домен
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.mamasha-mono-14rbed-backend.rule=Host(`sadovnick.store`) && PathPrefix(`/api`)"
      - "traefik.http.routers.mamasha-mono-14rbed-backend.entrypoints=websecure"
      - "traefik.http.routers.mamasha-mono-14rbed-backend.service=mamasha-mono-14rbed-backend"
      - "traefik.http.routers.mamasha-mono-14rbed-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.mamasha-mono-14rbed-backend.loadbalancer.server.port=4000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Фронтенд сервис
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://103.74.93.55:4001}
        - BACKEND_URL=${BACKEND_URL:-http://backend:4000}
    container_name: frontend
    restart: unless-stopped
    environment:
      # API URL для браузера (через домен)
      - NEXT_PUBLIC_API_URL=https://sadovnick.store
      - NEXT_PUBLIC_WS_URL=wss://sadovnick.store
      # Внутренний URL фронтенда для SSR запросов
      - FRONTEND_INTERNAL_URL=http://localhost:80
    ports:
      - "3003:80"
    depends_on:
      - backend
    networks:
      - garden-store-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  garden-store-network:
    driver: bridge
  dokploy-network:
    external: true

volumes:
  # Используем именованные volumes для данных
  backend-logs:
    driver: local
  backend-uploads:
    driver: local
