"""Add chat and chat_messages tables

Revision ID: 31ff11143f63
Revises: 8222a18e9d7f
Create Date: 2025-06-20 15:53:23.030812

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31ff11143f63"
down_revision: Union[str, None] = "8222a18e9d7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("unread_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("is_from_admin", sa.Boolean(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["public.chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["public.profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.drop_constraint(op.f("cart_items_user_id_fkey"), "cart_items", type_="foreignkey")
    op.drop_constraint(op.f("cart_items_product_id_fkey"), "cart_items", type_="foreignkey")
    op.create_foreign_key(
        None, "cart_items", "products", ["product_id"], ["id"], source_schema="public", referent_schema="public"
    )
    op.create_foreign_key(
        None, "cart_items", "profiles", ["user_id"], ["id"], source_schema="public", referent_schema="public"
    )
    op.drop_constraint(op.f("favourites_user_id_fkey"), "favourites", type_="foreignkey")
    op.drop_constraint(op.f("favourites_product_id_fkey"), "favourites", type_="foreignkey")
    op.create_foreign_key(
        None, "favourites", "products", ["product_id"], ["id"], source_schema="public", referent_schema="public"
    )
    op.create_foreign_key(
        None, "favourites", "profiles", ["user_id"], ["id"], source_schema="public", referent_schema="public"
    )
    op.drop_constraint(op.f("order_items_order_id_fkey"), "order_items", type_="foreignkey")
    op.create_foreign_key(
        None, "order_items", "orders", ["order_id"], ["id"], source_schema="public", referent_schema="public"
    )
    op.drop_constraint(op.f("orders_user_id_fkey"), "orders", type_="foreignkey")
    op.create_foreign_key(
        None, "orders", "profiles", ["user_id"], ["id"], source_schema="public", referent_schema="public"
    )
    op.drop_constraint(op.f("products_category_id_fkey"), "products", type_="foreignkey")
    op.create_foreign_key(
        None, "products", "categories", ["category_id"], ["id"], source_schema="public", referent_schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", schema="public", type_="foreignkey")
    op.create_foreign_key(op.f("products_category_id_fkey"), "products", "categories", ["category_id"], ["id"])
    op.drop_constraint(None, "orders", schema="public", type_="foreignkey")
    op.create_foreign_key(op.f("orders_user_id_fkey"), "orders", "profiles", ["user_id"], ["id"])
    op.drop_constraint(None, "order_items", schema="public", type_="foreignkey")
    op.create_foreign_key(op.f("order_items_order_id_fkey"), "order_items", "orders", ["order_id"], ["id"])
    op.drop_constraint(None, "favourites", schema="public", type_="foreignkey")
    op.drop_constraint(None, "favourites", schema="public", type_="foreignkey")
    op.create_foreign_key(op.f("favourites_product_id_fkey"), "favourites", "products", ["product_id"], ["id"])
    op.create_foreign_key(op.f("favourites_user_id_fkey"), "favourites", "profiles", ["user_id"], ["id"])
    op.drop_constraint(None, "cart_items", schema="public", type_="foreignkey")
    op.drop_constraint(None, "cart_items", schema="public", type_="foreignkey")
    op.create_foreign_key(op.f("cart_items_product_id_fkey"), "cart_items", "products", ["product_id"], ["id"])
    op.create_foreign_key(op.f("cart_items_user_id_fkey"), "cart_items", "profiles", ["user_id"], ["id"])
    op.drop_table("chat_messages", schema="public")
    op.drop_table("chats", schema="public")
    # ### end Alembic commands ###
